language: php
php:
    - 5.6
    - 7.0.12
    - 7.1

before_install:
    - sudo apt-get update > /dev/null
    # install Oracle JDK8
    - sh -c ./build/install-jdk.sh
    # install and launch neo4j
    - sh -c ./build/install-neo.sh
    - composer self-update

before_script:
    - composer install --prefer-dist --no-interaction

script:
    - vendor/bin/phpunit --exclude-group xml-mapping

notifications:
    email: "christophe@graphaware.com"
