site_name: GraphAware Neo4j PHP OGM Documentation
pages:
- Home: 'index.md'
- Overview:
  - 'What is Neo4j?': 'overview/what_is_neo4j.md'
  - 'What is an OGM?': 'overview/what_is_an_ogm.md'
- Getting started:
  - 'Tutorial': 'getting_started/tutorial.md'
- References:
  - 'Property Converters': 'references/property_converter.md'